service: slacker-nooze
custom:
  stage: ${opt:stage, self:provider.stage}
  environment: ${file(env.yml):${self:custom.stage}}

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  environment: # set env variables
    APP_SECRET: ${self:custom.environment.APP_SECRET}
    AUTHO_DOMAIN: ${self:custom.environment.AUTHO_DOMAIN}
    AUTHO_CLIENT_ID: ${self:custom.environment.AUTHO_CLIENT_ID}
    AUTHO_SECRET: ${self:custom.environment.AUTHO_SECRET}

myNextApplication: # set domain
  component: serverless-next.js
  inputs:
    domain: ['slacker-nooze', 'iandaley.ninja']

# Create resources with separate CloudFormation templates
resources:
  # Cognito
  - ${file(lib/deployment-resources/cognito-user-pool.yml)}
  - ${file(lib/deployment-resources/cognito-identity-pool.yml)}
